//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.VIETSACHes = new HashSet<VIETSACH>();
        }
    
        public string Masach { get; set; }
        public string Tensach { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public string MoTa { get; set; }
        public string MaNXB { get; set; }
        public Nullable<System.DateTime> NgayNhapHang { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string MaLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIETSACH> VIETSACHes { get; set; }
    }
}
